# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
require 'open-uri'
p "Creating users"

Teacher.destroy_all
User.destroy_all
Language.destroy_all
TeachersLanguage.destroy_all


user1 = User.create(username: "Marceau", email: "marceau@lewagon.com", password: "secret")

user2 = User.create(username: "Kévin", email: "kevin@lewagon.com", password: "secret")
user3 = User.create(username: "Mélanie", email: "melanie@lewagon.com", password: "secret")
user4 = User.create(username: "Christopher", email: "christopher@lewagon.com", password: "secret")
user5 = User.create(username: "Rayane", email: "rayane@lewagon.com", password: "secret")
user6 = User.create(username: "Mahdi", email: "mahdi@lewagon.com", password: "secret")
User.create(username: "Emy", email: "emy@lewagon.com", password: "secret")

p "Creating teachers"
teacher1 = Teacher.create(name: "Kalid", location: "Place des Quinconces, Bordeaux", price: rand(100..1000), user_id: rand(1..6))
teacher2 = Teacher.create(name: "Jérome", location: "Cours Victor Hugo, Bordeaux", price: rand(100..1000), user_id: rand(1..6))
teacher3 = Teacher.create(name: "Florian C", location: "Cours Portal, Bordeaux", price: rand(100..1000), user_id: rand(1..6))
teacher4 = Teacher.create(name: "Mathieu", location: "Quai Bacalan, Bordeaux", price: rand(100..1000), user_id: rand(1..6))
teacher5 = Teacher.create(name: "Patricia", location: "Quai de Paludate, Bordeaux", price: rand(100..1000), user_id: rand(1..6))
teacher6 = Teacher.create(name: "Kenzo", location: "Rue Gabriel Dedieu, Lormont", price: rand(100..1000), user_id: rand(1..6))
teacher7 = Teacher.create(name: "Théo", location: "Place de l'Europe, Ambarès", price: rand(100..1000), user_id: rand(1..6))
teacher8 = Teacher.create(name: "Adrien", location: "Rue Saint James, Bordeaux", price: rand(100..1000), user_id: rand(1..6))
teacher9 = Teacher.create(name: "Sophie", location: "Cours de l'Intendance, Bordeaux", price: rand(100..1000), user_id: rand(1..6))
teacher10 = Teacher.create(name: "Enor", location: "Esplanade des Antilles, Pessac", price: rand(100..1000), user_id: rand(1..6))
teacher11 = Teacher.create(name: "Brice", location: "Avenue du Maréchal de Lattre de Tassigny, Mérignac", price: rand(100..1000), user_id: rand(1..6))
teacher12 = Teacher.create(name: "Cyprien", location: "Avenue Charles de Gaulle, Bruges", price: rand(100..1000), user_id: rand(1..6))
teacher13 = Teacher.create(name: "Marc", location: "Place Gambetta, Le Bouscat", price: rand(100..1000), user_id: rand(1..6))
teacher14 = Teacher.create(name: "Paul-Henri", location: "Avenue Carnot, Cenon", price: rand(100..1000), user_id: rand(1..6))
teacher15 = Teacher.create(name: "Raja", location: "Avenue Jean Jaurès, Bassens", price: rand(100..1000), user_id: rand(1..6))
teacher16 = Teacher.create(name: "Raphaël", location: "Rue Calixte-Camelle, Bègles", price: rand(100..1000), user_id: rand(1..6))
teacher17 = Teacher.create(name: "Guilhem", location: "Rue des Faussets, Bordeaux", price: rand(100..1000), user_id: rand(1..6))
teacher18 = Teacher.create(name: "Benjamin", location: "Rue du Pas-Saint-Georges, Bordeaux", price: rand(100..1000), user_id: rand(1..6))
teacher19 = Teacher.create(name: "Taï", location: "Place du Palais, Bordeaux", price: rand(100..1000), user_id: rand(1..6))
teacher20 = Teacher.create(name: "Florian L", location: "Rue du Moulineau, Gradignan", price: rand(100..1000), user_id: rand(1..6))
teacher21 = Teacher.create(name: "Pierre", location: "Rue Sainte Catherine, Bordeaux", price: rand(100..1000), user_id: rand(1..6))
teacher22 = Teacher.create(name: "Humbert", location: "Route de Toulouse, Bordeaux", price: rand(100..1000), user_id: rand(1..6))
teacher23 = Teacher.create(name: "Farah", location: "Quai des Chartrons, Bordeaux", price: rand(100..1000), user_id: rand(1..6))
teacher24 = Teacher.create(name: "Nicolas", location: "Cours Balguerie Stuttenberg, Bordeaux", price: rand(100..1000), user_id: rand(1..6))
teacher25 = Teacher.create(name: "Océane", location: "Place Saint-Martial, Bordeaux", price: rand(100..1000), user_id: rand(1..6))
teacher26 = Teacher.create(name: "César", location: "Rue du Tondu, Bordeaux", price: rand(100..1000), user_id: rand(1..6))
teacher27 = Teacher.create(name: "Alexandre", location: "Place des Capucins, Bordeaux", price: rand(100..1000), user_id: rand(1..6))
teacher28 = Teacher.create(name: "Mehdi", location: "Rue des Menuts, Bordeaux", price: rand(100..1000), user_id: rand(1..6))
teacher29 = Teacher.create(name: "Desty", location: "Rue du Cloitre, Bordeaux", price: rand(100..1000), user_id: rand(1..6))
teacher30 = Teacher.create(name: "Kévin", location: "Quai Deschamps, Bordeaux", price: rand(100..1000), user_id: rand(1..6))
teacher31 = Teacher.create(name: "Fabien", location: "Quai de Brazza, Bordeaux", price: rand(100..1000), user_id: rand(1..6))

Language.create(name: "CSS")
Language.create(name: "HTML")
Language.create(name: "JS")
Language.create(name: "Rails")
Language.create(name: "Ruby")
Language.create(name: "React")
Language.create(name: "Python")
Language.create(name: "SQL")
Language.create(name: "C")
Language.create(name: "Java")
Language.create(name: "PHP")

TeachersLanguage.create(teacher_id: "1", language_id: "3")
TeachersLanguage.create(teacher_id: "1", language_id: "1")
TeachersLanguage.create(teacher_id: "1", language_id: "2")
TeachersLanguage.create(teacher_id: "2", language_id: "4")
TeachersLanguage.create(teacher_id: "2", language_id: "2")
TeachersLanguage.create(teacher_id: "2", language_id: "3")
TeachersLanguage.create(teacher_id: "3", language_id: "5")
TeachersLanguage.create(teacher_id: "3", language_id: "6")
TeachersLanguage.create(teacher_id: "3", language_id: "3")
TeachersLanguage.create(teacher_id: "4", language_id: "7")
TeachersLanguage.create(teacher_id: "4", language_id: "2")
TeachersLanguage.create(teacher_id: "4", language_id: "3")
TeachersLanguage.create(teacher_id: "5", language_id: "8")
TeachersLanguage.create(teacher_id: "5", language_id: "9")
TeachersLanguage.create(teacher_id: "5", language_id: "3")
TeachersLanguage.create(teacher_id: "6", language_id: "1")
TeachersLanguage.create(teacher_id: "6", language_id: "2")
TeachersLanguage.create(teacher_id: "6", language_id: "3")
TeachersLanguage.create(teacher_id: "7", language_id: "10")
TeachersLanguage.create(teacher_id: "7", language_id: "11")
TeachersLanguage.create(teacher_id: "7", language_id: "3")
TeachersLanguage.create(teacher_id: "8", language_id: "4")
TeachersLanguage.create(teacher_id: "8", language_id: "5")
TeachersLanguage.create(teacher_id: "8", language_id: "6")
TeachersLanguage.create(teacher_id: "9", language_id: "7")
TeachersLanguage.create(teacher_id: "9", language_id: "8")
TeachersLanguage.create(teacher_id: "9", language_id: "9")
TeachersLanguage.create(teacher_id: "10", language_id: "1")
TeachersLanguage.create(teacher_id: "10", language_id: "5")
TeachersLanguage.create(teacher_id: "10", language_id: "7")
TeachersLanguage.create(teacher_id: "11", language_id: "4")
TeachersLanguage.create(teacher_id: "11", language_id: "3")
TeachersLanguage.create(teacher_id: "11", language_id: "2")
TeachersLanguage.create(teacher_id: "12", language_id: "1")
TeachersLanguage.create(teacher_id: "12", language_id: "9")
TeachersLanguage.create(teacher_id: "12", language_id: "10")
TeachersLanguage.create(teacher_id: "13", language_id: "11")
TeachersLanguage.create(teacher_id: "13", language_id: "10")
TeachersLanguage.create(teacher_id: "13", language_id: "3")
TeachersLanguage.create(teacher_id: "14", language_id: "4")
TeachersLanguage.create(teacher_id: "14", language_id: "8")
TeachersLanguage.create(teacher_id: "14", language_id: "9")
TeachersLanguage.create(teacher_id: "15", language_id: "1")
TeachersLanguage.create(teacher_id: "15", language_id: "6")
TeachersLanguage.create(teacher_id: "15", language_id: "3")
TeachersLanguage.create(teacher_id: "16", language_id: "5")
TeachersLanguage.create(teacher_id: "16", language_id: "4")
TeachersLanguage.create(teacher_id: "16", language_id: "1")
TeachersLanguage.create(teacher_id: "17", language_id: "1")
TeachersLanguage.create(teacher_id: "17", language_id: "8")
TeachersLanguage.create(teacher_id: "17", language_id: "2")
TeachersLanguage.create(teacher_id: "18", language_id: "5")
TeachersLanguage.create(teacher_id: "18", language_id: "7")
TeachersLanguage.create(teacher_id: "18", language_id: "3")
TeachersLanguage.create(teacher_id: "19", language_id: "3")
TeachersLanguage.create(teacher_id: "19", language_id: "2")
TeachersLanguage.create(teacher_id: "19", language_id: "9")
TeachersLanguage.create(teacher_id: "20", language_id: "11")
TeachersLanguage.create(teacher_id: "20", language_id: "10")
TeachersLanguage.create(teacher_id: "20", language_id: "7")
TeachersLanguage.create(teacher_id: "21", language_id: "9")
TeachersLanguage.create(teacher_id: "21", language_id: "4")
TeachersLanguage.create(teacher_id: "21", language_id: "8")
TeachersLanguage.create(teacher_id: "22", language_id: "5")
TeachersLanguage.create(teacher_id: "22", language_id: "4")
TeachersLanguage.create(teacher_id: "22", language_id: "3")
TeachersLanguage.create(teacher_id: "23", language_id: "5")
TeachersLanguage.create(teacher_id: "23", language_id: "7")
TeachersLanguage.create(teacher_id: "23", language_id: "8")
TeachersLanguage.create(teacher_id: "24", language_id: "3")
TeachersLanguage.create(teacher_id: "24", language_id: "1")
TeachersLanguage.create(teacher_id: "24", language_id: "2")
TeachersLanguage.create(teacher_id: "25", language_id: "6")
TeachersLanguage.create(teacher_id: "25", language_id: "7")
TeachersLanguage.create(teacher_id: "25", language_id: "9")
TeachersLanguage.create(teacher_id: "26", language_id: "8")
TeachersLanguage.create(teacher_id: "26", language_id: "4")
TeachersLanguage.create(teacher_id: "26", language_id: "7")
TeachersLanguage.create(teacher_id: "27", language_id: "9")
TeachersLanguage.create(teacher_id: "27", language_id: "4")
TeachersLanguage.create(teacher_id: "27", language_id: "3")
TeachersLanguage.create(teacher_id: "28", language_id: "1")
TeachersLanguage.create(teacher_id: "28", language_id: "2")
TeachersLanguage.create(teacher_id: "28", language_id: "3")
TeachersLanguage.create(teacher_id: "29", language_id: "5")
TeachersLanguage.create(teacher_id: "29", language_id: "7")
TeachersLanguage.create(teacher_id: "29", language_id: "3")
TeachersLanguage.create(teacher_id: "30", language_id: "9")
TeachersLanguage.create(teacher_id: "30", language_id: "6")
TeachersLanguage.create(teacher_id: "30", language_id: "3")
TeachersLanguage.create(teacher_id: "31", language_id: "1")
TeachersLanguage.create(teacher_id: "31", language_id: "2")
TeachersLanguage.create(teacher_id: "31", language_id: "3")

p "Finished !"
